import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  FileText, 
  Upload, 
  MessageSquare, 
  History, 
  CheckCircle2, 
  AlertCircle, 
  Send,
  MoreVertical,
  Download,
  Info,
  ShieldCheck,
  FileCode,
  Image as ImageIcon
} from 'lucide-react';
import { cn } from '../lib/utils';

import { agencyTemplates } from '../data/templateData';

export default function ProjectVault() {
  const [activeTab, setActiveTab] = useState<'files' | 'comms' | 'templates'>('files');
  const [files, setFiles] = useState([
    { name: 'lead_gen_blueprint_rev4.pdf', date: '2h ago', size: '4.2MB', type: 'PDF', icon: FileText },
    { name: 'brand_assets_vector.zip', date: '1d ago', size: '115MB', type: 'ZIP', icon: ShieldCheck },
    { name: 'checkout_flow_logic.js', date: '3d ago', size: '12KB', type: 'JS', icon: FileCode },
    { name: 'hero_banner_preview.png', date: '5d ago', size: '2.8MB', type: 'IMG', icon: ImageIcon },
  ]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const newFile = {
        name: file.name,
        date: 'Just now',
        size: (file.size / (1024 * 1024)).toFixed(1) + 'MB',
        type: file.name.split('.').pop()?.toUpperCase() || 'FILE',
        icon: FileText
      };
      setFiles([newFile, ...files]);
    }
  };

  const handleDownloadStub = (name: string, type: string) => {
    const content = `Mock content for ${name} [${type}]\nGenerated by Flux Agency DevOps Platform.\nTimestamp: ${new Date().toISOString()}`;
    const mimeType = type === 'PDF' ? 'application/pdf' : type === 'DOCX' ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' : 'text/plain';
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = name;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-12 pb-24 font-sans">
      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-8 pt-6">
        <div>
           <h1 className="text-4xl font-display font-bold text-slate-900 dark:text-white tracking-tight uppercase">Project Vault</h1>
           <p className="text-slate-500 dark:text-slate-400 text-lg mt-2 font-medium">Synchronized asset repository and high-bandwidth strategy thread.</p>
        </div>
        <div className="flex gap-2 p-1 bg-slate-100 dark:bg-slate-900 rounded-2xl">
           {(['files', 'comms', 'templates'] as const).map(tab => (
             <button 
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={cn(
                "px-6 py-2.5 rounded-xl text-xs font-bold uppercase tracking-widest transition-all",
                activeTab === tab ? "bg-white dark:bg-[#020617] text-[#00AEEF] shadow-sm" : "text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
              )}
             >
               {tab === 'files' ? 'Assets' : tab === 'comms' ? 'Comms' : 'Blueprints'}
             </button>
           ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        {/* Main Interface */}
        <div className="lg:col-span-8 space-y-8">
           <AnimatePresence mode="wait">
             {activeTab === 'files' ? (
               <motion.div 
                 key="files"
                 initial={{ opacity: 0, x: -20 }}
                 animate={{ opacity: 1, x: 0 }}
                 exit={{ opacity: 0, x: 20 }}
                 className="space-y-6"
               >
                  <label className="card-agency p-12 border-dashed border-2 flex flex-col items-center justify-center text-center group cursor-pointer hover:border-orange-500/50 transition-all">
                     <input type="file" className="hidden" onChange={handleFileUpload} />
                     <div className="w-16 h-16 bg-slate-50 dark:bg-slate-900 rounded-full flex items-center justify-center text-slate-300 group-hover:text-orange-500 transition-colors mb-6">
                        <Upload size={32} />
                     </div>
                     <h3 className="text-xl font-bold text-slate-900 dark:text-white uppercase tracking-tighter">Push Strategic Assets</h3>
                     <p className="text-sm text-slate-400 mt-2 max-w-xs font-medium">Drag and drop CSV lists, Brand Kits, or API spreadsheets. Max 200MB/file.</p>
                  </label>

                  <div className="card-agency p-8 space-y-6">
                     <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Recent Deployments</h4>
                     <div className="space-y-4">
                        {files.map((file, i) => (
                           <FileItem key={i} {...file} onDownload={handleDownloadStub} />
                        ))}
                     </div>
                  </div>
               </motion.div>
             ) : activeTab === 'comms' ? (
               <motion.div 
                 key="comms"
                 initial={{ opacity: 0, x: 20 }}
                 animate={{ opacity: 1, x: 0 }}
                 exit={{ opacity: 0, x: -20 }}
                 className="card-agency p-0 flex flex-col h-[600px] overflow-hidden border-[#00AEEF]/20"
               >
                  <div className="p-6 border-b border-slate-100 dark:border-slate-900 flex items-center justify-between bg-slate-50/30 dark:bg-slate-900/30">
                     <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-[#FF6B00]/10 flex items-center justify-center text-[#FF6B00] font-black italic">SA</div>
                        <div>
                           <p className="text-sm font-black uppercase tracking-tighter">Strategic Advisor</p>
                           <p className="text-[10px] text-[#00AEEF] font-black uppercase tracking-[0.1em]">Neural Growth Architecture</p>
                        </div>
                     </div>
                     <div className="flex items-center gap-2">
                        <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />
                        <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Active Strategy Thread</span>
                     </div>
                  </div>

                  <div className="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar">
                     <Message bubble="left" text="System initialized. High-bandwidth strategy thread established. Assets synced with Project Vault." time="SYSTEM" />
                     <Message bubble="right" text="Establishing Weekly Growth Sync baseline. Please audit the Competitor Analysis Framework (XLSX) before the EOD sprint." time="09:12 AM" />
                     <Message bubble="left" text="Competitor Analysis neural mapping complete. ROI projections updated in the strategy layer. All assets sanitized." time="10:45 AM" />
                     <Message bubble="right" text="Proceed with expansion. Ensure Brand Voice Checklist is referenced for all AI-generated content workflows." time="11:02 AM" />
                  </div>

                  <div className="p-6 bg-slate-50/50 dark:bg-slate-950 border-t border-slate-100 dark:border-slate-900">
                     <div className="relative">
                        <textarea 
                           placeholder="Push message to Neural Strategy Layer..."
                           className="w-full bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 text-sm font-medium outline-none focus:border-[#00AEEF]/50 pr-16 h-28 resize-none shadow-sm transition-all"
                        />
                        <button className="absolute right-6 bottom-6 w-12 h-12 bg-[#FF6B00] text-white rounded-2xl shadow-xl shadow-orange-500/30 flex items-center justify-center hover:scale-105 active:scale-95 transition-all">
                           <Send size={20} />
                        </button>
                     </div>
                  </div>
               </motion.div>
             ) : (
               <motion.div 
                 key="templates"
                 initial={{ opacity: 0, y: 20 }}
                 animate={{ opacity: 1, y: 0 }}
                 exit={{ opacity: 0, y: -20 }}
                 className="grid grid-cols-1 md:grid-cols-2 gap-6"
               >
                  {agencyTemplates.map((template) => (
                    <div key={template.id} className="card-agency p-8 group cursor-pointer hover:border-[#00AEEF]/50 transition-all bg-white dark:bg-slate-950 shadow-sm hover:shadow-xl hover:shadow-[#00AEEF]/5 overflow-hidden relative">
                       <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-100 transition-opacity">
                          <FileText size={48} className="text-[#00AEEF]" />
                       </div>
                       <div className="flex justify-between items-start mb-6">
                          <span className="text-[10px] font-black text-white bg-slate-900 px-3 py-1 rounded-full uppercase tracking-widest">
                            {template.category.toUpperCase()}{template.type}
                          </span>
                       </div>
                       <h4 className="text-xl font-bold text-slate-900 dark:text-white uppercase tracking-tighter group-hover:text-[#00AEEF] transition-colors leading-tight">{template.name}</h4>
                       <p className="text-xs text-slate-500 mt-2 mb-8 font-medium leading-relaxed">{template.desc}</p>
                       <button 
                         onClick={() => handleDownloadStub(template.name + (template.type === 'PDF' ? '.pdf' : '.docx'), template.type)}
                         className="flex items-center gap-2 text-[10px] font-black text-[#FF6B00] uppercase tracking-[0.2em] hover:tracking-[0.25em] transition-all group-hover:translate-x-1"
                       >
                          <Download size={14} strokeWidth={3} /> Download Asset
                       </button>
                    </div>
                  ))}
               </motion.div>
             )}
           </AnimatePresence>
        </div>

        {/* Sidebar Constraints */}
        <div className="lg:col-span-4 space-y-8">
           <div className="card-agency p-8 bg-slate-950 text-white border-transparent shadow-2xl relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-32 h-32 bg-[#FF6B00]/5 -mr-16 -mt-16 rounded-full blur-3xl group-hover:bg-[#FF6B00]/20 transition-all duration-700" />
              <h4 className="text-xs font-black text-white/40 uppercase tracking-[0.3em] mb-8 flex items-center gap-3">
                 <ShieldCheck size={16} className="text-[#FF6B00]" /> File Security Protocols
              </h4>
              <ul className="space-y-8">
                 <ProtocolItem title="Sanitized Uploads" desc="All documents are scanned for malicious scripts before insertion." />
                 <ProtocolItem title="Access Control" desc="Only verified strategists and account admins can decrypt these files." />
                 <ProtocolItem title="Automated Versioning" desc="Every upload creates a new audit point. Revert to any state instantly." />
              </ul>
           </div>

           <div className="bg-white dark:bg-slate-950 rounded-[40px] p-8 border border-slate-200 dark:border-slate-800 shadow-sm">
              <h4 className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-6 flex items-center gap-3">
                 <Info size={16} className="text-[#00AEEF]" /> Upload Guidelines
              </h4>
              <div className="space-y-5">
                 <div className="flex items-start gap-4">
                    <div className="w-2 h-2 bg-[#FF6B00] rounded-full mt-1.5 flex-shrink-0" />
                    <p className="text-[11px] text-slate-600 dark:text-slate-400 font-bold uppercase tracking-tight leading-relaxed">Preferred formats: CSV, JSON, PNG, MP4, PDF</p>
                 </div>
                 <div className="flex items-start gap-4">
                    <div className="w-2 h-2 bg-[#FF6B00] rounded-full mt-1.5 flex-shrink-0" />
                    <p className="text-[11px] text-slate-600 dark:text-slate-400 font-bold uppercase tracking-tight leading-relaxed">Max file size limit for enterprise: 2GB per asset</p>
                 </div>
                 <div className="flex items-start gap-4">
                    <div className="w-2 h-2 bg-[#FF6B00] rounded-full mt-1.5 flex-shrink-0" />
                    <p className="text-[11px] text-slate-600 dark:text-slate-400 font-bold uppercase tracking-tight leading-relaxed">Compress large datasets to .zip for faster syncing</p>
                 </div>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}

function FileItem({ name, date, size, type, icon: Icon, onDownload }: any) {
  return (
    <div className="flex items-center justify-between p-4 rounded-2xl hover:bg-slate-50 dark:hover:bg-slate-900 transition-all group">
       <div className="flex items-center gap-4">
          <div className="w-10 h-10 bg-white dark:bg-slate-950 rounded-xl flex items-center justify-center text-slate-400 group-hover:text-orange-500 transition-colors shadow-sm">
             <Icon size={18} />
          </div>
          <div>
             <p className="text-sm font-bold text-slate-900 dark:text-white truncate max-w-[200px]">{name}</p>
             <p className="text-[10px] text-slate-400 font-bold uppercase">{date} • {size}</p>
          </div>
       </div>
       <div className="flex items-center gap-2">
          <span className="text-[8px] font-bold text-slate-400 px-2 py-0.5 border border-slate-100 dark:border-slate-800 rounded uppercase">{type}</span>
          <button 
            onClick={() => onDownload(name, type)}
            className="p-2 text-slate-300 hover:text-orange-500 transition-colors"
          >
             <Download size={16} />
          </button>
       </div>
    </div>
  );
}

function ProtocolItem({ title, desc }: any) {
  return (
    <div className="space-y-1">
       <h4 className="text-xs font-bold">{title}</h4>
       <p className="text-[10px] text-white/50 leading-relaxed">{desc}</p>
    </div>
  );
}

function Message({ bubble, text, time }: any) {
  return (
    <div className={cn(
      "flex flex-col max-w-[80%]",
      bubble === 'right' ? "ml-auto items-end" : "items-start"
    )}>
       <div className={cn(
         "p-4 rounded-[20px] text-sm",
         bubble === 'right' 
           ? "bg-orange-500 text-white rounded-br-none" 
           : "bg-slate-100 dark:bg-slate-900 text-slate-900 dark:text-slate-100 rounded-bl-none"
       )}>
          {text}
       </div>
       <span className="text-[9px] text-slate-400 font-bold uppercase mt-2">{time}</span>
    </div>
  );
}
